### PR TITLE
Allow to override the default D compiler

### PR DESCRIPTION
**Pull request by ximion**
This makes it possible to use the makefiles to compile this library with LDC and GDC too.

### CODE REVIEW

**Comment by ximion** [comment]
I thought about renaming it to DC, but I wasn't sure whether that would break other stuff.

**Comment by CyberShadow** [comment]
You can already override Makefile variables by specifying new values on the command line.

Such as: `make -f posix.mak DMD=gdmd`

This is why `DMD` is already in its own variable.

**Comment by ximion** [comment]
This works if you *explicitly* override the setting for make, but it would be much nicer if the script would just pick up whatever D compiler is set in the DMD/DC environment variable (try `DMD=ldmd2 make -f posix.mak`).

**Comment by CyberShadow** [comment]
> but it would be much nicer

Why is that?

I think using variables from the environment needs to be explicitly justified, as we don't want people to get different results from a build depending on what something else set in the environment. Especially with such a short variable name as `DC` I'm worried about accidental collisions.

Additionally using variables from the environment is not the pattern we use for building D components, where it's preferred that e.g. recursive make invocations explicitly pass whatever variables need to be forwarded to child make invocations.

**Comment by ximion** [comment]
For package build scripts we usually set compiler variables globally only once. There are tools which determine the default build flags and default compilers optimal for the architecture depending on distro policy and set them. So, `CFLAGS`, `CC`, `CXXFLAGS` etc. are usually set, and build systems pick them up and deal with them.
This allows e.g. to recompile the whole distribution with Clang by flipping a single switch, instead of patching loads of packages.

This change is not essential though, if you don't like it we could just catch the DC variable from the environment and pass it to make explicitly (even more so, since we don't use the makefiles for building in Debian, for us this isn't relevant at all - but it might be for others, which is the reason this PR exists)

**Comment by CyberShadow** [comment]
Is there any precedent or movement to standardize `DC` as the environment variable which indicates the command to use for the D compiler?

Note that setting `DC` to `gdc` or `ldc2` will not work, it would need to be `gdmd` or `ldmd2`, so that would need to be part of the accepted use of the variable.

**Comment by CyberShadow** [comment]
> Note that setting DC to gdc or ldc2 will not work, it would need to be gdmd or ldmd2, so that would need to be part of the accepted use of the variable.

BTW, for that reason, `DMD` might actually make more sense than `DC`, because (at least here) the variable is intended to indicate the name of an executable which supports DMD option syntax.

**Comment by ximion** [comment]
@CyberShadow Jup, there is no real standard for that - tbh, the difference in flags is annoying. One *could* always use ldmd/gdmd/dmd, but then you can't use other, compiler-specific flags, so using one of the wrapper is annoying in the distro case (also, gdmd doesn't seem to be shipped by Debian's GDC...).
Build systems like Meson detect the compiler based on the `DC` variable at time and then apply the right flags for it, so if you are not using a bare Makefile, this issue doesn't exist.

But again, even if a buildsystem is used, we'll get the same issue with the `DFLAGS` variable later :P 
It's messy, but manageable (D's ABI incompatibilities are much more annoying).

**Comment by CyberShadow** [comment]
Yep, I was thinking about `DFLAGS` as well - you can find instances of non-D-related projects using that variable occasionally.

> This makes it possible to use the makefiles to compile this library with LDC and GDC too.

OK, so we established that this wasn't the case, you just need to pass it to `make` explicitly.

> since we don't use the makefiles for building in Debian, for us this isn't relevant at all

OK. Considering that this change might have unexpected results, and it doesn't seem to solve any particular problem right now, I think the safe thing is to leave things as they are until a situation arises where such a change can improve things in practice. I know that @WalterBright is also not very fond of getting information from the environment where it's uncalled for (IIRC he was opposed to environment flags that control some Druntime behavior).

**Comment by ximion** [comment]
I think getting DFLAGS an DC from the environment is fine, for the rest I agree.

>> This makes it possible to use the makefiles to compile this library with LDC and GDC too.
> OK, so we established that this wasn't the case, you just need to pass it to make explicitly.

Jup - having to pass this manually was so unexpected for me that I thought it was unintended at first.

**Pull request closed without merging**
