### PR TITLE
add travis build status icon

### PR DESCRIPTION
**Pull request by John-Colvin**
~~there needs to be a new commit after travis is enabled for it to actually start testing, so why not have it be adding the status icon :)~~

Adds a test status icon to README.md

### CODE REVIEW

**Comment by WalterBright** [comment]
If this is to fix the travis build, why is it failing?

**Comment by John-Colvin** [comment]
@WalterBright this was just to make travis run. It doesn't address the fact that `undeaD` is full of errors. For that, see https://github.com/dlang/undeaD/pull/15/ which is WIP

**Comment by John-Colvin** [comment]
So now we get to see the failure of Travis, and why the D autotester is awesome because it doesn't have this problem\*. The fact that #15 was just merged in to master doesn't trigger a new merge test here. As a matter of fact there isn't a good way for a maintainer to run the right test at all. Simply re-running the test by clicking the button in Travis just re-runs with the same `git merge` as it had when the commits were pushed on *this* branch, oblivious to the new commits in `master`.

The only way to trigger the correct build is for new commits to be pushed to this branch. The easiest ways to do that are to amend the last commit without changing it or to rebase on to `master`. I will rebase this time.

\* It's also why the D autotester takes up a lot of resources, but that's the price you pay for being right.

**Comment by wilzbach** [comment]
> Simply re-running the test by clicking the button in Travis just re-runs with the same git merge as it had when the commits were pushed on this branch, oblivious to the new commits in master.

It's a bit off-topic, but for example DAutoTest runs `git merge` with the branch and that's something one can do with Travis as well. However of course it doesn't avoid the problem of rerunning the build whenever a new commit lands in master. Though it's quite easy to setup a hook, s.t. the Travis builds are automatically retriggered. We do sth. similar for the DLang tour ;-)

**Comment by John-Colvin** [comment]
ping. Merge?

**Pull request merged**
